[program:cofounder-backend]
command=/home/deployer/.nvm/versions/node/v20.20.1/bin/node dist/main.js

directory=/var/www/www.cofounder.icu/current/server
autostart=true
autorestart=true
startsecs=5
stopsignal=TERM
stopasgroup=true
killasgroup=true
user=deployer
environment=NODE_ENV="production"
stdout_logfile=/var/www/www.cofounder.icu/shared/logs/backend.stdout.log
stderr_logfile=/var/www/www.cofounder.icu/shared/logs/backend.stderr.log
stdout_logfile_maxbytes=20MB
stderr_logfile_maxbytes=20MB
stdout_logfile_backups=10
stderr_logfile_backups=10
