[program:cofounder-backend]
command=/usr/bin/node dist/main
directory=/var/www/www.cofounder.icu/current/server
autostart=true
autorestart=true
startsecs=5
stopsignal=TERM
stopasgroup=true
killasgroup=true
user=www-data
environment=NODE_ENV="production",PORT="3010"
stdout_logfile=/var/www/www.cofounder.icu/shared/logs/backend.stdout.log
stderr_logfile=/var/www/www.cofounder.icu/shared/logs/backend.stderr.log
stdout_logfile_maxbytes=20MB
stderr_logfile_maxbytes=20MB
stdout_logfile_backups=10
stderr_logfile_backups=10
